# Build stage
FROM maven:3.8.3-openjdk-17 AS build

# Set the working directory in the container
WORKDIR /sneakerFreaks

# Copy the project files into the container
COPY src ./src
COPY pom.xml .

# Build the application using Maven
RUN mvn clean package

# Expose the port on which the application will run
EXPOSE 8080

# Specify the command to run the application
ENTRYPOINT ["java", "-jar", "target/sneakerFreaks.jar"]
